### ISSUE TITLE
Serial service set-up.

### ISSUE THREAD

**Issue by AlksSAV** [GNSSOEM/ELT_RTKBase#10]
Here it is indicated that in order to activate the com port, you need to perform some manipulations with the Raspberry pi.
[Activation du port serie | Centipede RTK](https://docs.centipede.fr/docs/base/port_serie.html)
is this relevant for ERC as well, or are there other ways to configure it?

**Comment by Jef239** [comment]
This is done by [install_script.sh](https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/install_script.sh) during installation (running install.sh)

Look at the **check_boot_configiration** procedure
