### ISSUE TITLE
Antenna Information quotation marks

### ISSUE THREAD

**Issue by Rattall** [GNSSOEM/ELT_RTKBase#8]
ELT_RTKBase v1.7.0 Antenna info is sent with quotation marks “ADVNULLANTENNA” but should be send with out them ADVNULLANTENNA

![Capture_Original](https://github.com/user-attachments/assets/e6f4f7e2-b191-439f-b801-20d4e21780f7)

**Comment by Jef239** [comment]
Fixed in 1.7.1

https://github.com/GNSSOEM/ELT_RTKBase/commit/38f7c8bf24d64d120eb17f5d2b6a2bae53c3a504
