### ISSUE TITLE
Please add support for receivers from ComNav.

### ISSUE THREAD

**Issue by AlksSAV** [GNSSOEM/ELT_RTKBase#9]
it would be nice to add receivers from ComNav, for example the K803 model. It's a pretty common receiver. I have one, I could test the work.
![803](https://github.com/user-attachments/assets/ee6b2388-cf87-4b45-a9db-9830d2c27ab6)

**Comment by Jef239** [comment]
First of all - please give me a link to the description of its commands for setting up the receiver (command manual). I want to estimate the amount of work.

It seems to me to be too expensive for a base due to the presence of INS.

**Comment by AlksSAV** [comment]
Thanks for the reply. 
As for the price and place of purchase, I bought on Aliexpress the price was about $ 110
I would like to try to connect it myself, using your instructions. Perhaps it will be useful to others in the future.

**Comment by Jef239** [comment]
There are two ways - partial work and full adaptation. Partial work is possible both in ELT_RTKBase and in the original rtkbase from @Stefal.

Partial work plan.

1. Study the receiver and software for its configuration
2. Configure the output of RTCM3 packets, antenna type, approximate base coordinates
3. Connect the receiver to rtkbase. Receiver format: rtcm3, Receiver type: - should not start with Unicore, Bynav, Septentio.
4. Determine the exact coordinates of the base via NRCAN (described in the documentation).
5. Disconnect the receiver from rtbase, set the exact coordinates in the receiver using its own software.
6. Connect the receiver to rtkbase

What won't work:

1.  Detection
2. Configuration
3. Changing the receiver speed
4. Setting coordinates in the receiver
5. Setting the antenna name in the receiver
6. RTK.bat, HAS.bat

**Comment by Jef239** [comment]
Full adaptation plan

1. Study the receiver command system using the documentation
2. Explore the receiver experimentally to understand undocumented parts of the protocol, such as the execution time of long commands.
3. Write a file with commands for configuring the receiver. Example - https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/UM980_RTCM3_OUT.txt
4. Find or write a program that can configure the receiver using this file, waiting after each command for a response from the receiver, whether the command was executed successfully. The program should issue return codes. If the protocol is not too different from other receivers, maybe I can add this functionality to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/NmeaConf
5. Add to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/UnicoreConfigure.sh code for receiver detection and configuration.
6. Add to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/UnicoreSetBasePos.sh code for setting coordinates, antenna name, speed.
7. Add to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Windows/RTK.bat code for using the receiver as a rover.
8. Add code to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Windows/HAS.bat to use HAS (if the receiver supports HAS).

**Comment by Jef239** [comment]
I completely forgot. A plan for using the receiver's native protocol.

1. Study the receiver's command system using the documentation
2. Explore the receiver experimentally to understand undocumented parts of the protocol, such as the execution time of long commands.
3. Write a file with commands to configure the receiver. Example - https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/UM980_RTCM3_OUT.txt
4. Find or write a program that can configure the receiver using this file, waiting after each command for a response from the receiver, whether the command was executed successfully. The program should issue return codes. If the protocol is not too different from other receivers, maybe I can add this functionality to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/NmeaConf
5. Add to RTKLIB or rtklibexplorer conversion of the native protocol to RTCM3.
6. Add to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/UnicoreConfigure.sh code for detecting and configuring the receiver.
7. Add to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/UnicoreSetBasePos.sh code for changing the speed.
8. Add to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Windows/RTK.bat code for using the receiver as a rover.
9. Add code to https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Windows/HAS.bat to use HAS (if the receiver supports HAS).

**Comment by Jef239** [comment]
Well, here you go. I wrote three plans. Is the scope of work clear? :-)

Personally, I recommend partial adaptation, it's easier, but not everything will work. For example, I connected Quectel LG290P according to this plan. But we were not satisfied with the characteristics of this receiver and the number of errors in it.

**Comment by AlksSAV** [comment]
I'll try, maybe it will work.
